---
abstract: 'Yet Another RESTful-Archive Service Client'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Cwd: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yars-Client
requires:
  Clustericious::Client: 0.82
  Clustericious::Client::Command: 0
  Clustericious::Config: 0.25
  Clustericious::Log: 0
  Data::Dumper: 0
  Digest::file: 0
  File::Basename: 0
  File::Spec: 0
  IO::Uncompress::Gunzip: 0
  Log::Log4perl: 0
  Log::Log4perl::CommandLine: 0
  Mojo::Asset::File: 0
  Mojo::Base: 0
  Mojo::ByteStream: 0
  Mojo::URL: 0
  Mojolicious: 4.00
  Number::Bytes::Human: 0.09
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/yars-client/issues
  homepage: http://perl.wdlabs.com/Yars-Client/
  repository: git://github.com/plicease/yars-client.git
version: 0.93
